// Mocks generated by Mockito 5.1.0 from annotations
// in recru_test/test/repository/recruiters_repository_local_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:recru_test/model/recruiter.dart' as _i4;

import 'recruiters_repository_local_test.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [RecruitersRepositoryTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockRecruitersRepositoryTest extends _i1.Mock
    implements _i2.RecruitersRepositoryTest {
  MockRecruitersRepositoryTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Recruiter>> getRecruiters(String? query) =>
      (super.noSuchMethod(Invocation.method(#getRecruiters, [query]),
              returnValue: Future<List<_i4.Recruiter>>.value(<_i4.Recruiter>[]))
          as _i3.Future<List<_i4.Recruiter>>);
}
